---

- hosts: all
  become: true
  tasks:  

  - name: install apache and php for CentOS server
    package: 
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  
