---

- hosts: all
  become: true
  tasks:  


  - name: install apache2 package
    yum: 
      name: httpd  
      state: absent  

  - name: add php support for apache
    yum:
      name: php
      state: absent    
